### ISSUE TITLE
Chapter 8 should give full build instructions

### ISSUE THREAD

**Issue by codygman** [paf31/purescript-book#44]
To allow people who are jumping around to have it "just work". For instance, I went directly to chapter 8 since I wanted to learn how to wrap an external javascript library.

I cloned this repo, opened the chapter 8 directory, and:

```
~/s/purescript-book/chapter8:master* λ bower update
~/s/purescript-book/chapter8:master* λ pulp browserify --to dist/Main.js 
* Browserifying project in /home/cody/source/purescript-book/chapter8
* Building project in /home/cody/source/purescript-book/chapter8
* Build successful.
* Browserifying...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'react-dom' from '/home/cody/source/purescript-book/chapter8/output/ReactDOM'
    at /home/cody/.npm-packages/lib/node_modules/pulp/node_modules/resolve/lib/async.js:46:17
    at process (/home/cody/.npm-packages/lib/node_modules/pulp/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/cody/.npm-packages/lib/node_modules/pulp/node_modules/resolve/lib/async.js:188:17)
    at load (/home/cody/.npm-packages/lib/node_modules/pulp/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/cody/.npm-packages/lib/node_modules/pulp/node_modules/resolve/lib/async.js:92:31)
    at /home/cody/.npm-packages/lib/node_modules/pulp/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

It would have saved me about 20 minutes if I'd seen:

For those jumping chapter to chapter, before building you'll need to `npm install react react-dom`.

I actually only got my answer after googling that error and finding [some irc history](http://chrisdone.com:10001/browse/purescript?events_page=8045).
Thoughts?

**Comment by paf31** [comment]
Fixed in the new version, thanks!
